#!/bin/bash

set -e
set -u
set -o pipefail

DISTS="stretch
testing
unstable
latest
"

ARCH="$1"

if [ "$ARCH" != "arm64" ]; then
    DISTS="$DISTS
    jessie
    "
fi

BASENAME=jbbgameich/minideb
GCR_BASENAME=gcr.io/bitnami-containers/minideb
QUAY_BASENAME=quay.io/bitnami/minideb

if [ -n "${DOCKER_PASSWORD:-}" ]; then
    echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
fi

if [ -n "${QUAY_PASSWORD:-}" ]; then
    docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io
fi

if [ -n "${GCR_KEY:-}" ]; then
    gcloud auth activate-service-account "$GCR_EMAIL" --key-file <(echo "$GCR_KEY")
fi

ENABLE_DOCKER_CONTENT_TRUST=0
if [ -n "${DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE:-}" -a -n "${DOCKER_CONTENT_TRUST_REPOSITORY_KEY:-}" ]; then
    tmpdir=$(mktemp -d)
    (cd "${tmpdir}" && bash -c 'echo -n "${DOCKER_CONTENT_TRUST_REPOSITORY_KEY}" | base64 -d > key')
    chmod 400 "${tmpdir}/key"
    docker trust key load "${tmpdir}/key"
    rm -rf "${tmpdir}"
    export ENABLE_DOCKER_CONTENT_TRUST=1
fi

for DIST in $DISTS; do
    DOCKER_CONTENT_TRUST=${ENABLE_DOCKER_CONTENT_TRUST} docker push "${BASENAME}:${DIST}-${ARCH}"
done
